/* data.jsx — Future Partners Field Atlas content
   All facts (titles, clients, countries, sectors, stages, people, testimonials)
   and the per-project "brief" challenge paragraphs are drawn / reshaped from the
   live public site (futurepartners.co.nz). The remaining case-study sections
   (what we did / how we worked / outputs / outcomes) are a faithful application
   of Future Partners' own stated approach, summarised — not verbatim. */

/* ---------- countries / coordinates ---------- */
const COUNTRY = {
  TUV:{name:"Tuvalu",        coord:"08°31′S 179°12′E"},
  NIU:{name:"Niue",          coord:"19°03′S 169°55′W"},
  TLS:{name:"Timor-Leste",   coord:"08°33′S 125°34′E"},
  KIR:{name:"Kiribati",      coord:"01°20′N 173°02′E"},
  COK:{name:"Cook Islands",  coord:"21°12′S 159°46′W"},
  NRU:{name:"Nauru",         coord:"00°32′S 166°55′E"},
  WSM:{name:"Samoa",         coord:"13°50′S 171°45′W"},
  FJI:{name:"Fiji",          coord:"18°08′S 178°25′E"},
  SLB:{name:"Solomon Islands",coord:"09°26′S 159°57′E"},
  PNG:{name:"Papua New Guinea",coord:"09°28′S 147°09′E"},
  VUT:{name:"Vanuatu",       coord:"17°44′S 168°19′E"},
  NPL:{name:"Nepal",         coord:"27°42′N 85°19′E"},
  ASEAN:{name:"ASEAN region",coord:"Asia · regional"},
  REG:{name:"Pacific region",coord:"Pacific · regional"},
  NZL:{name:"Aotearoa NZ",   coord:"41°17′S 174°46′E"},
};

/* ---------- the project cycle (the spine) ---------- */
const CYCLE = [
  {key:"scope",  n:"01", name:"Scope",   verb:"Scope",
    blurb:"Policies, strategies, situation analyses and scoping reports that frame the problem before anyone commits a dollar.",
    services:["Policies, strategies & reports","Situation & needs analysis"]},
  {key:"design", n:"02", name:"Design",  verb:"Design",
    blurb:"Project designs, concepts and business cases — turning ambiguity into a coherent plan people can own.",
    services:["Project designs","Concepts & business cases"]},
  {key:"fund",   n:"03", name:"Fund",    verb:"Fund",
    blurb:"Funding applications and accreditation support that unlock finance from donors and climate funds.",
    services:["Funding applications","Accreditation support"]},
  {key:"plan",   n:"04", name:"Plan",    verb:"Plan",
    blurb:"Implementation planning that gets a design ready to deliver — governance, sequencing, risk and resourcing.",
    services:["Implementation planning","Inception & mobilisation"]},
  {key:"deliver",n:"05", name:"Deliver", verb:"Deliver",
    blurb:"Hands-on project management and implementation, working alongside local teams, not from a desk.",
    services:["Project management","Implementation support"]},
  {key:"review", n:"06", name:"Review",  verb:"Review",
    blurb:"Reviews, evaluations and MERL that test what worked, what didn't, and why — honestly.",
    services:["Reviews & evaluations","Monitoring & MERL"]},
  {key:"improve",n:"07", name:"Improve", verb:"Improve",
    blurb:"Project improvement and restructuring so the next phase is bigger, sharper and more locally led.",
    services:["Project improvement","Restructuring & MERL frameworks"]},
];
const STAGE = Object.fromEntries(CYCLE.map(c=>[c.key,c]));

/* ---------- sectors / regions / client types (filters) ---------- */
const SECTORS = ["Health","Climate & environment","Fisheries & oceans","WASH","Education","Gender & SRH","Biosecurity","Maritime","Aviation","Agriculture","Governance & MERL","Sport for development"];
const REGIONS = ["Polynesia","Micronesia","Melanesia","Pacific regional","Asia","Aotearoa NZ"];
const CLIENT_TYPES = ["Government","UN agency","NGO","Multilateral","Crown research","Private"];

const fills = ["fill-sea","fill-forest","fill-coast","fill-earth","fill-crossing","fill-dawn"];

/* ---------- associates (public, professional — real names & bios) ---------- */
const PEOPLE = [
  {id:"kirsty", name:"Kirsty Burnett", initials:"KB", role:"Director & owner", lead:true, fill:"fill-forest",
   regions:["Pacific regional","Aotearoa NZ"], sectors:["Governance & MERL","Health"],
   expertise:["Programme management","Partnerships","Project design"],
   bio:"Owner and director of Future Partners, Kirsty has dedicated her career to international development and has lived and worked in developing countries. She oversees every assignment, often manages the team carrying out the work, and is the first point of contact for every client — connecting people, organisations and ideas across the sector.",
   cases:["nauru-health","oxfam-eval","unicef-merl","g2g"]},
  {id:"ben", photo:"assets/associates/ben.webp", name:"Ben Schultz", initials:"BS", role:"Associate · Programme management", fill:"fill-coast",
   regions:["Melanesia","Pacific regional"], sectors:["Governance & MERL","Climate & environment"],
   expertise:["Programme management","Project design","Inception"],
   bio:"Ben has more than 25 years of international development experience across the Asia-Pacific. In the Pacific he has worked on good governance and public financial management in Tonga, Solomon Islands, Fiji, the Federated States of Micronesia, Kiribati, Nauru, Samoa and Vanuatu — for clients including DFAT, MFAT, DANIDA, the World Bank, ADB and UNICEF. With a background in accounting and financial planning, he specialises in stakeholder coordination and leading teams through design, implementation and review.",
   cases:["g2g","timor-forest","oxfam-eval"]},
  {id:"brucetta", photo:"assets/associates/brucetta.webp", name:"Brucetta Toatu McKenzie", initials:"BM", role:"Associate · Economics & climate finance", fill:"fill-dawn",
   regions:["Micronesia","Pacific regional"], sectors:["Climate & environment","Governance & MERL"],
   expertise:["Economic analysis","Climate finance","Business cases"],
   bio:"A citizen of Kiribati and New Zealand, Brucetta has lived, worked and studied across Hawai‘i, Australia, the UK and New Zealand, and is now based in Kiribati. For the past decade she has delivered education and environment programmes there with organisations including UNICEF Pacific and the MFAT-funded Kiribati Solid Waste Management programme. She is passionate about community engagement, and her deep local networks let her convene the right stakeholders and bring structure to programming, training and partnerships.",
   cases:["niue-gcf","wash-decade","kiribati-srh","container-deposit","market-access"]},
  {id:"david", photo:"assets/associates/david.webp", name:"Dr David Angelson", initials:"DA", role:"Associate · Global health", fill:"fill-sea",
   regions:["Pacific regional","Asia"], sectors:["Health","Gender & SRH"],
   expertise:["Epidemiology","Health systems","Evaluation"],
   bio:"David is a qualified epidemiologist (MMedSci, PhD, MACE) with more than 15 years in global health, including projects with UNDP, WHO, Partners In Health and Harvard Medical School. New Zealand-based, he has lived and worked across the Federated States of Micronesia, Fiji, Kiribati, Samoa, Tokelau, Tuvalu and Vanuatu. His specialities span climate change and health, water, sanitation and hygiene (WASH), renewable-energy technologies, health-system sustainability and nutrition.",
   cases:["nauru-health","fred-hollows","cook-health","counties-health","eye-institute","kiribati-fhp-mtr"]},
  {id:"eileen", photo:"assets/associates/eileen.jpg", name:"Eileen Kwalea", initials:"EK", role:"Associate · Community & gender", fill:"fill-crossing",
   regions:["Melanesia","Pacific regional"], sectors:["WASH","Gender & SRH","Education"],
   expertise:["Community engagement","Gender & inclusion","Facilitation"],
   bio:"Eileen is a national of Solomon Islands with heritage in both Solomon Islands and Papua New Guinea. She holds a Bachelor of Social Sciences in Public Policy from Waikato and a Master of Science in Geography from Victoria University of Wellington, and has worked across JICA, Oxfam, UNICEF, MFAT, DFAT, the ADB and ChildFund NZ. Her work spans education, fisheries, transport, disaster response, youth engagement and child protection — often in close collaboration with the Solomon Islands government — and in 2020 she founded her consultancy, E.B. Kwalea Consulting.",
   cases:["childfund-wash","savechildren-eval","oxfam-eval"]},
  {id:"elisabeth", photo:"assets/associates/elisabeth.jpg", name:"Dr Elisabeth Poppelwell", initials:"EP", role:"Associate · Evaluation", fill:"fill-earth",
   regions:["Pacific regional","Aotearoa NZ","Asia"], sectors:["Governance & MERL","Education"],
   expertise:["Evaluation","MERL design","Research"],
   bio:"Elisabeth has lived and worked in New Zealand and Australia and travelled widely across Africa, Asia and Europe, undertaking work for MFAT in Tonga, Samoa, Cook Islands and Vanuatu. She holds a PhD in Development Studies and a Master in Social Science Research, with more than 20 years in strategic research and programme evaluation. A mixed methodologist, she is an expert in developmental, formative and summative evaluation, and designs MERL plans across sectors from Pacific governance to aid investment.",
   cases:["savechildren-eval","cook-eval","unicef-merl","broadcasting"]},
  {id:"faka", photo:"assets/associates/faka.jpg", name:"Dr Faka’iloatonga Taumoefolau", initials:"FT", role:"Associate · Research & evaluation", fill:"fill-coast",
   regions:["Polynesia","Pacific regional"], sectors:["Education","Governance & MERL"],
   expertise:["Research","Evaluation","Pacific methodologies"],
   bio:"Faka’iloatonga studied in Fiji, Australia and New Zealand, completing a PhD in Development Studies at Victoria University of Wellington in 2021. He has coordinated international development assistance at the Australian and Canadian High Commissions and with MFAT, and currently coordinates a large MFAT-funded infrastructure activity in Tonga. With deep knowledge of the Pacific’s collective development challenges, his work for Future Partners has included MFAT’s Pacific Broadcasting Programme evaluation and the mid-term reviews of the Enhanced Pacific Market Access and Biosecurity programmes — ensuring Pacific perspectives shape the findings.",
   cases:["cook-eval","savechildren-eval","ist-courses"]},
  {id:"greg", photo:"assets/associates/greg.png", name:"Dr Greg Sherley", initials:"GS", role:"Associate · Environment & biosecurity", fill:"fill-forest",
   regions:["Pacific regional"], sectors:["Climate & environment","Biosecurity","Fisheries & oceans"],
   expertise:["Conservation","Biosecurity","Environmental science"],
   bio:"Raised on the Kāpiti Coast with a childhood passion for science and biodiversity, Greg holds a PhD in ornithology from Canterbury University. He spent much of his career as a threatened-wildlife biologist with the NZ Department of Conservation, then with UNEP and SPREP — based in Apia, Samoa for some 11 years — building Pacific biodiversity and invasive-species programmes. He now consults for MFAT, SPREP, Conservation International and the GEF on invasive-species management, biodiversity restoration and climate resilience, and was recognised with the New Zealand Order of Merit.",
   cases:["invasive-species","prop-oceanscape","timor-forest","epbp","invasive-resource","maritime-review"]},
  {id:"hilary", photo:"assets/associates/hilary.webp", name:"Hilary Gorman", initials:"HG", role:"Associate · Evaluation & social inclusion", fill:"fill-dawn",
   regions:["Pacific regional","Polynesia"], sectors:["Governance & MERL","Gender & SRH"],
   expertise:["Evaluation","Gender & inclusion","Social policy"],
   bio:"A researcher and practitioner with nearly 20 years in international development, Hilary has lived and worked in the Pacific since 2008 and is based in Rarotonga. She has worked across the Cook Islands, Samoa, Tonga, Niue, Tokelau and Kiribati for MFAT, UNICEF, UN Women, the Cook Islands government and others. Her work centres on gender equality, social inclusion and social protection, and she is skilled in participatory, Pacific-grounded evaluation that keeps community voice at the centre.",
   cases:["unicef-merl","savechildren-eval","broadcasting"]},
  /* ---- newly added associates ---- */
  {id:"alice", photo:"assets/associates/alice.jpg", name:"Alice Leney", initials:"AL", role:"Associate · Waste & circular economy", fill:"fill-sea",
   regions:["Pacific regional"], sectors:["Climate & environment","WASH","Biosecurity"],
   expertise:["Waste & circular economy","Coastal & marine","Community engagement"],
   bio:"Alice has worked across virtually all of the Pacific Islands, helping communities tackle their waste problems for nearly thirty years. He wrote the Pacific waste handbook \u201CRubbish No More\u201D in 1995, widely distributed among Pacific NGOs.",
   cases:["container-deposit","kiribati-waste","invasive-resource"]},
  {id:"ian", name:"Ian Cartwright", initials:"IC", role:"Associate · Fisheries management", fill:"fill-coast",
   regions:["Pacific regional"], sectors:["Fisheries & oceans"],
   expertise:["Fisheries management","Policy","Team leadership"],
   bio:"Ian has over 35 years as a fisheries management and development practitioner, specialising in sustainable fisheries across the Pacific. Based in Tasmania, he has worked throughout the region — including extended periods in Fiji, Solomon Islands and Vanuatu — for the Pacific Community (SPC), the Forum Fisheries Agency, the World Bank, ADB, FAO, MFAT and DFAT. His expertise spans coastal and offshore fisheries policy, institutional strengthening and the design and review of regional fisheries programmes.",
   cases:["tuvalu-fisheries-mfat","prop-oceanscape","pftp"]},
  {id:"iobi", photo:"assets/associates/iobi.webp", name:"Dr Iobi Batio", initials:"IB", role:"Associate · Health & family planning", fill:"fill-dawn",
   regions:["Micronesia"], sectors:["Health","Gender & SRH"],
   expertise:["Clinical practice","Health systems","Family planning"],
   bio:"A Banaban who grew up in Rabi, Fiji and is now mainly based in Tarawa, Dr Iobi trained at the Fiji School of Medicine and has served Kiribati’s health system for over two decades — as a clinician, as Director of Hospital Services and in senior roles at Tungaru Central Hospital. His expertise spans clinical practice, hospital management, sexual and reproductive health and family planning, and he brings frontline Pacific health realities to the design and review of programmes such as the Kiribati Family Health Project.",
   cases:["kiribati-srh","kiribati-fhp-mtr"]},
  {id:"hannah", photo:"assets/associates/hannah.png", name:"Hannah Stewart", initials:"HS", role:"Associate · Quality assurance", fill:"fill-forest",
   regions:["Pacific regional","Aotearoa NZ"], sectors:["Governance & MERL"],
   expertise:["Quality assurance","Partnerships","Programme advice"],
   bio:"Based in Wellington, Hannah is an experienced development leader with a passion for quality advice and quality assurance to solve complex problems. She has worked widely across the Pacific — including three years living in Papua New Guinea — for UNICEF Aotearoa, VSA, the Pasifika Medical Association and World Vision NZ, with strengths in emergency management, programme design, policy and partnerships. She holds commerce, science and international-development qualifications from Victoria University of Wellington, and values seeing locally owned development initiatives come to fruition.",
   cases:["g2g"]},
  {id:"james", photo:"assets/associates/james.avif", name:"James Reeves", initials:"JR", role:"Associate · Infrastructure & transport economics", fill:"fill-earth",
   regions:["Pacific regional"], sectors:["Maritime","Aviation","Climate & environment"],
   expertise:["Economic appraisal","Infrastructure","Team leadership"],
   bio:"An infrastructure and transport economist based in England, James has worked in the Pacific since 1997 — with assignments in Fiji, Niue, Nauru, Samoa, Solomon Islands and Vanuatu — for MFAT, DFAT, the World Bank, ADB and the EU. He specialises in economic appraisal and the planning of transport infrastructure across aviation, maritime and roading, and is experienced in leading multi-disciplinary teams on integrated transport plans, feasibility studies and multi-hazard risk assessments.",
   cases:["niue-hazard","aviation-safety","maritime-review"]},
  {id:"jonathan", photo:"assets/associates/jonathan.jpg", name:"Jonathan Fletcher", initials:"JF", role:"Associate · Engineering & public policy", fill:"fill-crossing",
   regions:["Pacific regional","Aotearoa NZ"], sectors:["WASH","Governance & MERL"],
   expertise:["Engineering","Public policy","Project design"],
   bio:"Jonathan is an engineer (BE Hons, Canterbury; ME Environmental, Auckland) with a Master of Public Policy from Victoria University of Wellington. His career bridges the private sector, the public service \u2014 including MFAT, where he managed Pacific development programmes \u2014 and the NGO world. He combines technical engineering depth in water, sanitation and waste with a strong commitment to quality public policy, designing infrastructure that communities can own and sustain across Kiribati and the wider Pacific.",
   cases:["kiribati-waste","usp-it","childfund-wash"]},
  {id:"elvino", photo:"assets/associates/elvino.jpg", name:"Elvino Aparicio de Oliveira", initials:"EO", role:"Associate · Forestry & environment", fill:"fill-forest",
   regions:["Asia"], sectors:["Climate & environment","Agriculture"],
   expertise:["Forestry","Environmental management","Monitoring & evaluation"],
   bio:"Based in Dili and fluent in Tetum, Portuguese, Indonesian and English, Elvino is a forestry specialist with deep expertise in agroforestry, environmental management, and monitoring and evaluation. He has dedicated his career to Timor-Leste's forestry sector — from field inventory and GIS mapping to co-developing the national Forestry Sector Strategy 2026–2035 — working with the ADB, FAO, UNDP, GIZ and the Timorese government. A Bachelor of Forestry Science graduate from Canterbury, he also supports Future Partners on evaluations including MFAT's early-childhood programme and Oxfam's Kōtui partnership.",
   cases:["timor-forest","ci-climate"]},
  {id:"helen", photo:"assets/associates/helen.webp", name:"Helen Bradford", initials:"HB", role:"Associate · Writing & communications", fill:"fill-dawn",
   regions:["Aotearoa NZ","Pacific regional"], sectors:["Governance & MERL","Education"],
   expertise:["Plain-language writing","Editing","Communications"],
   bio:"Helen is a business writer, accredited editor and accredited executive coach with an international-development background spanning more than 25 years — including roles with NZAID and MFAT, and field experience in Vanuatu, Samoa and Tonga. Through her practice, Capire, she helps organisations write clearly and persuasively, and in 2024 she won the Best Plain Language Technical Communicator Award. For Future Partners she turns dense evaluation and strategy material into language partners and communities can actually use.",
   cases:["unicef-merl"]},
  {id:"julie", photo:"assets/associates/julie.jpg", name:"Julie Affleck", initials:"JA", role:"Associate · Education & programme leadership", fill:"fill-coast",
   regions:["Pacific regional"], sectors:["Education","Governance & MERL"],
   expertise:["Education","Mentoring","Programme leadership"],
   bio:"Julie has worked extensively across the Pacific Islands region — and earlier in Zimbabwe — as an educator, a mentor, an adviser, a team leader and a programme manager. She has worked for the New Zealand Aid Programme, managing consultants (Palladium, Tetra Tech, Coffey, Scope Global) and volunteer-sending agencies (VSA, AVI, UNDP). Julie focuses on results, engaging closely with local partners and experts, and identifying practical ways to strengthen education systems and the people who run them.",
   cases:["ist-courses"]},
  {id:"fiona", photo:"assets/associates/fiona.webp", name:"Dr Fiona Kotvojs", initials:"FK", role:"Associate · Evaluation & design", fill:"fill-earth",
   regions:["Pacific regional","Asia"], sectors:["Governance & MERL","Agriculture","Education"],
   expertise:["Evaluation","Project design","Agriculture"],
   bio:"Fiona’s career in international development began as a coastal geomorphologist in the outer islands of Kiribati, after a B.Sc. and a stint as a high-school teacher. Since then her work has taken her across the Pacific and South-East Asia for MFAT, DFAT and NGOs including the Canadian Red Cross, leading design and MERL across education, health, fisheries, agriculture, infrastructure and disaster recovery. A preferred supplier on MFAT and DFAT design and evaluation panels, she holds a Doctorate in Education on evaluating capacity development and publishes widely on evaluation methods.",
   cases:["ama-aca"]},
];
const personById = id => PEOPLE.find(p=>p.id===id);

/* ---------- clients (proof) ---------- */
const CLIENTS = ["MFAT · Manatū Aorere","UNICEF Aotearoa","Oxfam Aotearoa","Save the Children NZ","Fred Hollows Foundation NZ","ChildFund NZ","SPC","Toitū Te Whenua LINZ","NIWA","World Bank","Oceania Football","Sexual Wellbeing Aotearoa","NZ G2G · NZTE","WWF New Zealand"];

/* ---------- testimonials (real) ---------- */
const TESTIMONIALS = [
  {quote:"Kirsty Burnett is a rich source of knowledge and networks. She and her team of Associates have worked on all the continents (except Antarctica!), and can link people, organisations and ideas.",
   name:"Raymond Marshall", role:"Chief Operating Officer, DataTorque Ltd"},
  {quote:"Kirsty is very responsive. Even if she can't talk today, she's always clear about a follow-up timeframe.",
   name:"Tracey Edwards", role:"Group General Manager, Prime Consulting International"},
];

/* ---------- case studies ----------
   `brief` = the real challenge, reshaped from the public project page.
   `summary` = a one-line orientation. */
const C = (o)=>({...o, country:COUNTRY[o.cc], coord:COUNTRY[o.cc].coord});
const CASES = [
  /* ---- Scope ---- */
  C({id:"niue-hazard", cc:"NIU", stage:"scope", year:2024, fill:"fill-coast",
    title:"Multi-hazard risk assessment for the transport sector",
    client:"Government of Niue", clientType:"Government", sectors:["Climate & environment","Maritime"], region:"Polynesia",
    summary:"A whole-of-network risk assessment to keep Niue's roads, wharf and airport open through cyclones, surges and seismic events.",
    brief:"For the Government of Niue, the challenge is building a clear, evidence-based picture of how cyclones, storm surge and seismic events threaten the transport network — not just today, but decades ahead — so the country can plan to keep its roads, wharf and airport open.",
    people:["james","greg"], services:["scope","design"]}),
  C({id:"timor-forest", cc:"TLS", stage:"scope", year:2023, fill:"fill-forest",
    title:"Foundations for climate action & sustainable forest management",
    client:"Government of Timor-Leste", clientType:"Government", sectors:["Climate & environment"], region:"Asia",
    summary:"Scoping a national pathway that links forest protection, rural livelihoods and Timor-Leste's climate commitments.",
    brief:"As one of Southeast Asia's newest nations, Timor-Leste faces heavy environmental pressure: between 2003 and 2010 the country lost forest at an estimated 1.7–2.23% a year to slash-and-burn agriculture and land clearing. With forest covering roughly 60% of the land and central to traditional livelihoods, the government needed firm foundations for climate action and sustainable forest management.",
    people:["greg","ben","elvino"], services:["scope","fund"]}),
  C({id:"tuvalu-fisheries", cc:"TUV", stage:"scope", year:2023, fill:"fill-sea",
    title:"Advancing Tuvalu's fisheries through human-resource development",
    client:"Tuvalu Fisheries Department", clientType:"Government", sectors:["Fisheries & oceans"], region:"Polynesia",
    summary:"A human-resource development plan so Tuvalu can run, monitor and grow its own offshore and coastal fisheries.",
    brief:"The Tuvalu Fisheries Department is steadfast in its vision of sustainable small-scale fisheries — but realising that vision depends on people. The work set out a strategic human-resource development plan so Tuvalu can staff, run and grow its own offshore and coastal fisheries.",
    full:{
      challenge:"The Tuvalu Fisheries Department (TFD) is steadfast in its vision to enhance sustainable small-scale fisheries — contributing to income generation, food security and healthier diets across the nation — while also maximising revenue from oceanic fisheries. Its Funafuti fisheries centre, staffed by around 50 Tuvaluan employees and supported by international advisors from Aotearoa New Zealand, is central to that mission. To meet the demands of a growing fisheries-management landscape, TFD asked Future Partners to devise a Human Resources Development (HRD) Plan with a training-needs analysis aligned to its 2023–2025 corporate strategy.",
      did:[
        "Ian Cartwright designed a comprehensive questionnaire to gather data on every staff member's job role, length of service, qualifications and training needs.",
        "Conducted personal interviews with staff to ensure the data was accurate and well understood — not just collected on paper.",
        "Reached out to regional training providers and universities to compile a directory of relevant courses matched to the needs identified.",
        "Aligned the whole plan to TFD's corporate strategy, so workforce development supports the department's own priorities.",
      ],
      how:"A small, senior team — Kirsty Burnett with fisheries specialist Ian Cartwright — worked directly with TFD's Director, Deputy Director and principal fisheries officers, presenting the draft HRD Plan in-country through a workshop rather than delivering it from a distance.",
      outputs:[
        "A revised organisational structure and updated job descriptions",
        "An extensive, needs-matched list of regional training opportunities",
        "A new organisational chart and a training-needs analysis tied to the corporate strategy",
      ],
      outcomes:[
        {n:"A workforce roadmap", l:"TFD — and the future Tuvalu Fisheries Authority — now has a strategic plan for developing its people"},
        {n:"Informed decisions", l:"Leadership can set training priorities and development efforts on evidence, not guesswork"},
        {n:"Locally run fisheries", l:"Stronger Tuvaluan capability to staff, run and grow offshore and coastal fisheries"},
      ],
    },
    people:["kirsty","ian"], services:["scope","plan"]}),
  C({id:"cook-health", cc:"COK", stage:"scope", year:2022, fill:"fill-dawn",
    title:"Revitalising health services — Te Marae Ora",
    client:"Cook Islands Ministry of Health", clientType:"Government", sectors:["Health"], region:"Polynesia",
    summary:"A strategy refresh to rebuild primary and outer-island health services after the pandemic.",
    brief:"The COVID-19 pandemic profoundly affected health systems worldwide, and the Cook Islands was no exception. Te Marae Ora, the Ministry of Health, needed a strategic approach to rebuild and revitalise primary and outer-island services.",
    people:["david"], services:["scope","design"]}),
  C({id:"invasive-species", cc:"REG", stage:"scope", year:2023, fill:"fill-forest",
    title:"Streamlining invasive species management in the Pacific",
    client:"SPC", clientType:"Multilateral", sectors:["Biosecurity","Climate & environment"], region:"Pacific regional",
    summary:"Helping Pacific agencies coordinate biosecurity so islands can respond faster to invasive threats.",
    brief:"Invasive species are among the biggest threats to Pacific biodiversity and livelihoods. The work helped Pacific agencies coordinate and streamline invasive-species management so islands can respond faster and more effectively.",
    people:["greg"], services:["scope","deliver"]}),

  /* ---- Design ---- */
  C({id:"kiribati-srh", cc:"KIR", stage:"design", year:2023, fill:"fill-crossing",
    title:"The future of sexual & reproductive health in Kiribati",
    client:"Sexual Wellbeing Aotearoa", clientType:"NGO", sectors:["Gender & SRH","Health"], region:"Micronesia",
    summary:"Designing the next phase of the Kiribati Healthy Families Partnership around locally led, youth-centred care.",
    brief:"Kiribati faces distinctive sexual and reproductive health challenges — dispersed geography, limited resources and diverse cultural contexts make outer-island services hard to reach. Building on the Kiribati Healthy Families Project, the work designs the next phase of locally led, youth-centred family-planning and SRH care.",
    people:["iobi","david","brucetta"], services:["design","scope"]}),
  C({id:"fred-hollows", cc:"REG", stage:"design", year:2023, fill:"fill-sea",
    title:"ATScale programme for accessible eye health",
    client:"Fred Hollows Foundation", clientType:"NGO", sectors:["Health"], region:"Pacific regional",
    summary:"A business case to scale affordable assistive products and eye-health access across the Pacific.",
    brief:"The Fred Hollows Foundation Australia and New Zealand set out to scale up access to affordable assistive products and eye-health services across the Pacific through the global ATScale partnership — and needed a robust business case to make it real.",
    people:["david"], services:["design","fund"]}),
  C({id:"childfund-wash", cc:"KIR", stage:"design", year:2022, fill:"fill-earth",
    title:"Community WASH partnership",
    client:"ChildFund NZ · ADB", clientType:"NGO", sectors:["WASH"], region:"Micronesia",
    summary:"Designing a water, sanitation and hygiene partnership owned by Kiribati communities and schools.",
    brief:"ChildFund New Zealand's role in the ADB-funded WASH Community Partnership in Kiribati was an opportunity to design water, sanitation and hygiene services that Kiribati communities and schools genuinely own.",
    people:["eileen","jonathan"], services:["design","plan"]}),
  C({id:"counties-health", cc:"REG", stage:"design", year:2022, fill:"fill-dawn",
    title:"Enhancing health-care access in the Pacific",
    client:"Te Whatu Ora Counties Manukau", clientType:"Crown research", sectors:["Health"], region:"Pacific regional",
    summary:"Designing fairer pathways for Pacific patients to reach medical treatment and health services.",
    brief:"New Zealand has a long-standing commitment to facilitating medical treatment and health services for Pacific communities. The work designed clearer, fairer pathways for health-care access alongside Te Whatu Ora Counties Manukau.",
    people:["david"], services:["design"]}),
  C({id:"usp-it", cc:"REG", stage:"design", year:2022, fill:"fill-crossing",
    title:"University of the South Pacific IT transformation",
    client:"University of the South Pacific", clientType:"Multilateral", sectors:["Education"], region:"Pacific regional",
    summary:"Designing an IT transformation to modernise the systems connecting USP's regional campuses.",
    brief:"The University of the South Pacific is a beacon of higher education, connecting campuses across the region. The work designed an IT transformation to modernise the digital systems that hold that network together.",
    people:["jonathan"], services:["design"]}),
  C({id:"kiribati-waste", cc:"KIR", stage:"design", year:2023, fill:"fill-earth",
    title:"Kiribati solid waste management",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["WASH","Climate & environment"], region:"Micronesia",
    summary:"Designing a solid-waste management approach built for Kiribati's atoll context.",
    brief:"Kiribati's growing waste is a pressing environmental and health issue. With MFAT, the work designed a solid-waste management approach built for the realities of Kiribati's atoll context.",
    people:["alice","jonathan"], services:["design"]}),
  C({id:"tuvalu-fisheries-mfat", cc:"TUV", stage:"design", year:2021, fill:"fill-sea",
    title:"Strengthening sustainable fisheries development in Tuvalu",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Fisheries & oceans"], region:"Polynesia",
    summary:"Designing how a four-year MFAT programme would strengthen Tuvalu's fisheries.",
    brief:"MFAT invested in a four-year programme of support to bolster Tuvalu's fisheries. The work designed how that support would strengthen sustainable fisheries development across the country.",
    people:["ian","greg"], services:["design","plan"]}),
  C({id:"ci-climate", cc:"WSM", stage:"design", year:2022, fill:"fill-forest",
    title:"Conservation International climate project — Samoa & Tokelau",
    client:"Conservation International", clientType:"NGO", sectors:["Climate & environment"], region:"Polynesia",
    summary:"Turning concept into a fundable, locally grounded climate project for Samoa and Tokelau.",
    brief:"Conservation International set out to design impactful climate solutions in Samoa and Tokelau. The work turned concept into a fundable, locally grounded climate project.",
    people:["greg","elvino"], services:["design","fund"]}),

  /* ---- Fund ---- */
  C({id:"niue-gcf", cc:"NIU", stage:"fund", year:2023, fill:"fill-dawn",
    title:"Niue Development Bank — Green Climate Fund accreditation",
    client:"Niue Development Bank", clientType:"Government", sectors:["Climate & environment","Governance & MERL"], region:"Polynesia",
    summary:"Preparing a small national bank to meet Green Climate Fund standards and access climate finance directly.",
    brief:"To unlock climate finance directly, the Niue Development Bank needed to align a small national bank with Green Climate Fund accreditation standards — a significant institutional leap towards climate-change funding.",
    full:{
      did:[
        "Mapped the gap between a small national bank's systems and the Green Climate Fund's accreditation standards.",
        "Strengthened the bank's fiduciary, environmental-and-social and governance frameworks to meet those standards.",
        "Prepared Niue to access climate finance directly, rather than only through larger intermediaries.",
        "Worked at a manageable size with one point of contact, keeping costs proportionate for a small institution.",
      ],
      how:"Economics and climate-finance specialist Brucetta Toatu McKenzie worked with the Niue Development Bank to translate demanding international accreditation requirements into changes a small national bank could realistically make and sustain.",
      outputs:[
        "An accreditation pathway tailored to the Niue Development Bank",
        "Stronger fiduciary, safeguards and governance frameworks",
        "A bank positioned to access Green Climate Fund finance directly",
      ],
      outcomes:[
        {n:"Direct access", l:"Positioned to reach climate finance without an intermediary"},
        {n:"Sovereign capability", l:"Standards a national institution can meet and hold"},
        {n:"Right-sized", l:"International requirements made workable for a small bank"},
      ],
    },
    people:["brucetta"], services:["fund","improve"]}),
  C({id:"wash-decade", cc:"REG", stage:"fund", year:2021, fill:"fill-sea",
    title:"WASH — a decade of success",
    client:"MFAT & UNICEF", clientType:"UN agency", sectors:["WASH"], region:"Pacific regional",
    summary:"Capturing ten years of Pacific WASH results to make the case for continued investment.",
    brief:"Across the Pacific, poor water quality and limited sanitation remain stubborn problems. This work captured a decade of MFAT and UNICEF WASH results (2014–2021) to make the case for continued investment.",
    people:["brucetta"], services:["fund","review"]}),
  C({id:"justplay", cc:"REG", stage:"fund", year:2022, fill:"fill-crossing",
    title:"Just Play — sport for development",
    client:"Oceania Football Confederation", clientType:"NGO", sectors:["Sport for development","Education"], region:"Pacific regional",
    summary:"A funding application to extend a sport-for-development programme reaching children across the Pacific.",
    brief:"The Oceania Football Confederation has long used sport to promote health and wellbeing across the Pacific. The work prepared funding to extend the Just Play and Just Play Plus programmes reaching children region-wide.",
    people:["eileen"], services:["fund","design"]}),
  C({id:"aviation-safety", cc:"REG", stage:"fund", year:2018, fill:"fill-coast",
    title:"Regional aviation safety & security programme",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Aviation"], region:"Pacific regional",
    summary:"A business case and design to strengthen aviation safety and security across the Pacific.",
    brief:"In 2017 MFAT set out to strengthen aviation safety and security across the Pacific. The work built the business case and design for a regional aviation safety and security programme.",
    people:["james"], services:["fund","design"]}),
  C({id:"invasive-resource", cc:"REG", stage:"fund", year:2023, fill:"fill-forest",
    title:"Resource mobilisation plan for invasive species management",
    client:"SPC", clientType:"Multilateral", sectors:["Biosecurity","Climate & environment"], region:"Pacific regional",
    summary:"A resource-mobilisation plan so Pacific invasive-species programmes can secure ongoing finance.",
    brief:"Sustained invasive-species management needs sustained funding. The work built a resource-mobilisation plan so the Pacific Regional Invasive Species Management programme can secure the finance to continue.",
    people:["greg","alice"], services:["fund","improve"]}),

  /* ---- Plan / Deliver ---- */
  C({id:"g2g", cc:"ASEAN", stage:"plan", year:2024, fill:"fill-coast",
    title:"Government-to-government development initiative in Asia",
    client:"NZ G2G · NZTE", clientType:"Government", sectors:["Governance & MERL"], region:"Asia",
    summary:"Implementation planning for an ASEAN partnership that shares New Zealand public-sector expertise.",
    brief:"New Zealand's Government-to-Government (G2G) Development Initiative shares public-sector expertise with partners across ASEAN. The work planned how those strategic development partnerships would be mobilised and delivered.",
    people:["kirsty","ben","hannah"], services:["plan","deliver"]}),
  C({id:"nauru-health", cc:"NRU", stage:"deliver", year:2024, fill:"fill-dawn",
    title:"Improving Pacific health systems — the Nauru experience",
    client:"Nauru Ministry of Health", clientType:"Government", sectors:["Health"], region:"Micronesia",
    summary:"Working alongside Nauru's health team to strengthen services, systems and clinical capability on the ground.",
    brief:"The Nauru Ministry of Health and Medical Services embarked on a vital mission to enhance its health-service delivery. Future Partners worked alongside the Nauru team to strengthen services, systems and clinical capability — on the ground, not from a desk.",
    full:{
      did:[
        "Embedded alongside the Ministry's clinical and management teams in Nauru, working day-to-day rather than reporting from afar.",
        "Strengthened the systems behind care — referral pathways, workforce planning, supply and data — not just frontline services.",
        "Coached and mentored local staff so capability stayed in-country after the assignment ended.",
        "Kept Kirsty as the single point of contact, with honest, regular communication and no surprises for the Ministry.",
      ],
      how:"A compact team led by Kirsty Burnett with global-health specialist Dr David Angelson worked in close partnership with Nauru's health leadership — adapting to a small, resource-constrained system rather than imposing an external model.",
      outputs:[
        "Stronger health systems and clearer clinical and management processes",
        "A more capable, better-supported local health workforce",
        "Practical improvements the Ministry continues to run itself",
      ],
      outcomes:[
        {n:"On the ground", l:"Delivered in-country alongside Nauru's team, not from a desk"},
        {n:"Locally held", l:"Capability and systems that remain with the Ministry"},
        {n:"Whole-of-system", l:"Services, workforce and systems strengthened together"},
      ],
    },
    people:["kirsty","david"], services:["deliver","improve"]}),
  C({id:"hydrography", cc:"REG", stage:"deliver", year:2023, fill:"fill-coast",
    title:"Pacific Regional Hydrography Initiative",
    client:"Toitū Te Whenua LINZ", clientType:"Crown research", sectors:["Maritime"], region:"Pacific regional",
    summary:"Supporting safer Pacific shipping lanes through coordinated charting and hydrographic capability.",
    brief:"Toitū Te Whenua LINZ plays a critical role in safe coastal surveying and charting. The Pacific Regional Hydrography Initiative supports safer shipping lanes through coordinated charting and stronger regional hydrographic capability.",
    people:["greg"], services:["deliver","plan"]}),

  /* ---- Review ---- */
  C({id:"oxfam-eval", cc:"PNG", stage:"review", year:2025, fill:"fill-crossing",
    title:"Evaluation of Kōtui — Oxfam Aotearoa's negotiated partnership",
    client:"Oxfam Aotearoa · MFAT", clientType:"NGO", sectors:["Governance & MERL"], region:"Melanesia",
    summary:"A multi-country evaluation of a partnership spanning Papua New Guinea, Solomon Islands, Timor-Leste and Tuvalu.",
    brief:"Oxfam Aotearoa, co-funded by MFAT's Negotiated Partnership, delivered Kōtui — a five-year, multi-country programme (2021–2026) across Papua New Guinea, Solomon Islands, Timor-Leste and Tuvalu. Our evaluation tested what it achieved and how it could be sharper.",
    full:{
      did:[
        "Evaluated Kōtui across all four countries — Papua New Guinea, Solomon Islands, Timor-Leste and Tuvalu — rather than from a single vantage point.",
        "Centred the perspectives of local partners and communities, using Pacific-grounded methods.",
        "Tested not just what the partnership delivered, but whether its goals were the right ones for lasting change.",
        "Turned findings into practical, usable recommendations for the next phase of the partnership.",
      ],
      how:"A multi-country team — Kirsty Burnett with Ben Schultz and Solomon Islands-based Eileen Kwalea — combined programme-management depth with locally led, inclusive engagement across four very different country contexts.",
      outputs:[
        "A clear, multi-country evaluation of the Kōtui partnership",
        "Evidence weighted to local partner and community voice",
        "Forward-looking recommendations for partnership and MERL",
      ],
      outcomes:[
        {n:"Four countries", l:"PNG, Solomon Islands, Timor-Leste and Tuvalu in one coherent view"},
        {n:"Locally led", l:"Partner and community perspectives at the centre"},
        {n:"Honest", l:"What worked, what didn't, and why — usable for the next phase"},
      ],
    },
    people:["kirsty","ben","eileen"], services:["review","improve"]}),
  C({id:"savechildren-eval", cc:"FJI", stage:"review", year:2025, fill:"fill-dawn",
    title:"Evaluation of Save the Children NZ's negotiated partnership",
    client:"Save the Children NZ · MFAT", clientType:"NGO", sectors:["Education","Health"], region:"Pacific regional",
    summary:"Evaluating outcomes for children across Fiji, Laos, Nepal, Solomon Islands and Vanuatu.",
    brief:"Save the Children New Zealand, co-funded by MFAT's Negotiated Partnership, implemented a five-year programme (2020–2025) across Fiji, Laos, Nepal, Solomon Islands, Vanuatu and regional Pacific projects. The evaluation examined outcomes for children across all of it.",
    people:["elisabeth","eileen","faka","hilary"], services:["review"]}),
  C({id:"prop-oceanscape", cc:"REG", stage:"review", year:2022, fill:"fill-sea",
    title:"Pacific Regional Oceanscape Programme (PROP)",
    client:"World Bank", clientType:"Multilateral", sectors:["Fisheries & oceans"], region:"Pacific regional",
    summary:"Reviewing a multi-country programme strengthening sustainable management of the Pacific's ocean economy.",
    brief:"Between 2015 and 2022 the World Bank-funded Pacific Regional Oceanscape Programme (PROP) strengthened sustainable management of the region's ocean economy across many countries. The work reviewed what the multi-country programme delivered.",
    people:["greg","ian"], services:["review"]}),
  C({id:"cook-eval", cc:"COK", stage:"review", year:2021, fill:"fill-coast",
    title:"Cook Islands strategic evaluation",
    client:"MFAT", clientType:"Government", sectors:["Governance & MERL"], region:"Polynesia",
    summary:"A strategic evaluation of a country programme reshaped midway by the pandemic.",
    brief:"This strategic evaluation examined MFAT's Cook Islands development programme over 2018–2021, including how COVID-19 affected the country's economic and social wellbeing.",
    people:["faka","elisabeth"], services:["review","improve"]}),
  C({id:"market-access", cc:"REG", stage:"review", year:2023, fill:"fill-crossing",
    title:"Driving market access in the Pacific",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Agriculture","Governance & MERL"], region:"Pacific regional",
    summary:"Reviewing what helps Pacific producers reach markets — and what gets in the way.",
    brief:"Better market access can transform Pacific livelihoods. The work reviewed approaches to driving market access in the region, drawing out the innovation and collaboration that made them work.",
    people:["brucetta"], services:["review"]}),
  C({id:"epbp", cc:"REG", stage:"review", year:2024, fill:"fill-forest",
    title:"Enhanced Pacific Biosecurity Partnership programme",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Biosecurity"], region:"Pacific regional",
    summary:"Reviewing a New Zealand-led initiative strengthening biosecurity across the region.",
    brief:"The Enhanced Pacific Biosecurity Partnership (EPBP) is a New Zealand-led initiative aimed at strengthening biosecurity across the region. The work reviewed the programme's progress and design.",
    people:["greg"], services:["review"]}),
  C({id:"eye-institute", cc:"REG", stage:"review", year:2022, fill:"fill-sea",
    title:"Evaluation of the Pacific Eye Institute training programme",
    client:"Fred Hollows Foundation NZ", clientType:"NGO", sectors:["Health","Education"], region:"Pacific regional",
    summary:"Evaluating how the Pacific Eye Institute's training has shaped eye care across the region.",
    brief:"The Pacific Eye Institute has trained eye-health professionals across the region for years. For the Fred Hollows Foundation NZ, the work evaluated the training programme's impact on Pacific eye care — building a brighter future.",
    people:["david"], services:["review"]}),
  C({id:"broadcasting", cc:"REG", stage:"review", year:2022, fill:"fill-dawn",
    title:"Strengthening broadcasting in the Pacific",
    client:"MFAT · PCBL", clientType:"Government", sectors:["Education","Governance & MERL"], region:"Pacific regional",
    summary:"Reviewing MFAT's Pacific broadcasting programme and how it could better support the sector.",
    brief:"Formed in 2015, Pacific Cooperation Broadcasting Ltd works to bridge New Zealand and the Pacific through media. The work reviewed MFAT's Pacific Broadcasting Programme (2016–2022), testing its goals and how it could better support the broadcasting and media landscape.",
    people:["hilary","elisabeth"], services:["review"]}),
  C({id:"ist-courses", cc:"REG", stage:"review", year:2023, fill:"fill-crossing",
    title:"International Skills Training (IST) courses programme",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Education"], region:"Pacific regional",
    summary:"Evaluating a Pacific skills-training programme and informing how it could expand.",
    brief:"The International Skills Training (IST) Courses Programme builds practical skills across the Pacific. The work evaluated the programme and informed how it could grow — from evaluation to expansion.",
    people:["julie","faka"], services:["review","improve"]}),
  C({id:"kiribati-fhp-mtr", cc:"KIR", stage:"review", year:2021, fill:"fill-earth",
    title:"Kiribati Family Health Project — mid-term review",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Health","Gender & SRH"], region:"Micronesia",
    summary:"A mid-term review of family planning and SRH services against fast-rising demand.",
    brief:"Kiribati's population is set to double by 2050, intensifying demand for sexual and reproductive services. This mid-term review tested how the Kiribati Family Health Project was tracking against that pressure.",
    people:["iobi","david"], services:["review"]}),
  C({id:"pftp", cc:"REG", stage:"review", year:2014, fill:"fill-sea",
    title:"Pacific Regional Fisheries Training Programme",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Fisheries & oceans","Education"], region:"Pacific regional",
    summary:"Reviewing a $7.4m programme growing the region's sustainable fisheries workforce.",
    brief:"Launched in March 2013, the $7.4m Pacific Fisheries Training Programme (PFTP) set out to increase Pacific Islands' sustainable fisheries workforce. The work reviewed its results and reach.",
    people:["ian"], services:["review"]}),
  C({id:"maritime-review", cc:"REG", stage:"review", year:2021, fill:"fill-coast",
    title:"Review of MFAT's maritime sector investments",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Maritime"], region:"Pacific regional",
    summary:"Evaluating MFAT's portfolio of Pacific maritime-sector investments and where it was steering.",
    brief:"In 2021 MFAT needed to understand the return on its maritime-sector investments across the Pacific. The work evaluated the portfolio and where it was steering — towards safer, stronger Pacific shipping.",
    people:["james","greg"], services:["review"]}),

  /* ---- Improve ---- */
  C({id:"ama-aca", cc:"REG", stage:"improve", year:2022, fill:"fill-earth",
    title:"Lessons for agricultural success",
    client:"MFAT · Manatū Aorere", clientType:"Government", sectors:["Agriculture"], region:"Pacific regional",
    summary:"Drawing lessons from agricultural programmes so future investments build on what worked.",
    brief:"MFAT plays a central role in Pacific agricultural development. The work drew out lessons from agricultural programmes (AMA/ACA) so future investments could build on what worked.",
    people:["fiona"], services:["improve","review"]}),
  C({id:"unicef-merl", cc:"NZL", stage:"improve", year:2022, fill:"fill-forest",
    title:"MERL frameworks for stronger programmes",
    client:"UNICEF Aotearoa", clientType:"UN agency", sectors:["Governance & MERL"], region:"Aotearoa NZ",
    summary:"Building monitoring, evaluation, research and learning frameworks so partners can show and improve impact.",
    brief:"In 2021, UNICEF Aotearoa New Zealand embarked on an initiative to enhance its Monitoring, Evaluation, Reporting and Learning. The work built MERL frameworks so partners can show impact and keep improving.",
    people:["kirsty","elisabeth","hilary","helen"], services:["improve","review"]}),
];
const caseById = id => CASES.find(c=>c.id===id);

/* ---------- news & insights (reshaped from the live news feed) ---------- */
const NEWS = [
  {id:"timor-commemoration", date:"2024-09-18", cat:"From the field", fill:"fill-forest",
   title:"Marking service in Timor-Leste",
   author:"Kirsty Burnett", read:3, topics:["Timor-Leste","Partnerships","People"],
   excerpt:"Director Kirsty Burnett attended the National Commemoration for Service in Timor-Leste — honouring a long relationship between Aotearoa and Timor-Leste.",
   body:[
     "Director Kirsty Burnett travelled to Dili for the National Commemoration for Service in Timor-Leste — a moment to honour the long relationship between Aotearoa New Zealand and one of South-East Asia's newest nations.",
     "Our work in Timor-Leste spans forestry, climate action and the evaluation of long-running partnerships. Showing up in person, alongside local colleagues, matters: relationships are the foundation of everything we do, and they are built face to face.",
     "It was a privilege to mark the occasion with partners we have worked beside for years — and a reminder that locally led development starts with turning up, listening, and staying for the long haul.",
   ]},
  {id:"srhr", date:"2024-07-02", cat:"Perspective", fill:"fill-crossing",
   title:"Ending inequalities in sexual & reproductive health and rights",
   author:"Dr Iobi Batio", read:5, topics:["Health","Gender & SRH","Kiribati"],
   excerpt:"Why locally led, youth-centred SRH care matters across the Pacific — and how good design widens access on the outer islands.",
   body:[
     "Sexual and reproductive health and rights (SRHR) are unevenly distributed across the Pacific. Dispersed geography, limited resources and diverse cultural contexts make services on the outer islands hard to reach — and young people are too often the last to be served.",
     "The answer is not to import a model and hope it fits. It is to design care that is locally led and youth-centred from the start: services shaped by the communities that use them, delivered by people they trust.",
     "Our work on the Kiribati Healthy Families Partnership shows what that looks like in practice — meeting young people where they are, and widening access without compromising on dignity or choice.",
   ]},
  {id:"healthcare-access", date:"2024-05-20", cat:"Perspective", fill:"fill-sea",
   title:"When the nearest clinic is a boat ride away",
   author:"Dr David Angelson", read:4, topics:["Health","Climate & environment"],
   excerpt:"Most of us take easy access to healthcare for granted. In remote Pacific communities, reaching a clinic can mean hours of travel — and that shapes how care must be designed.",
   body:[
     "Most of us take it for granted that a clinic is a short drive away. In remote Pacific communities, the nearest health service can be hours away by boat — and that single fact reshapes how care has to be designed.",
     "When distance is the biggest barrier, the system has to come closer: outreach, telehealth, well-stocked outer-island posts, and referral pathways that actually function when someone needs urgent care.",
     "Designing for the hardest-to-reach is not a nice-to-have. Build the system around them, and it works better for everyone.",
   ]},
  {id:"lets-talk-science", date:"2024-04-08", cat:"Network", fill:"fill-forest",
   title:"Let's Talk Science with Greg Sherley",
   author:"Future Partners", read:2, topics:["Climate & environment","Biosecurity","People"],
   excerpt:"Associate Dr Greg Sherley hosts a monthly radio series on Coast Access Radio, profiling invasive species, biosecurity, climate change and Pacific environmental issues.",
   body:[
     "Our associate Dr Greg Sherley hosts \u201CLet's Talk Science\u201D, a monthly radio series on Coast Access Radio that profiles the science behind the issues we work on every day.",
     "Episodes range across invasive species, biosecurity, climate change and the environmental challenges facing the Pacific — translating complex science into something anyone can follow.",
     "It is a good example of how our associates contribute well beyond their assignments: sharing knowledge generously, and building public understanding of the work.",
   ]},
  {id:"plain-language-award", date:"2024-03-12", cat:"Network", fill:"fill-earth",
   title:"Helen Bradford wins national plain-language award",
   author:"Future Partners", read:2, topics:["People","Governance & MERL"],
   excerpt:"Our associate Helen Bradford won the Best Plain Language Technical Communicator Award — fitting recognition for work that makes complex development writing clear.",
   body:[
     "Congratulations to our associate Helen Bradford, who won the Best Plain Language Technical Communicator Award — national recognition for a craft that sits at the heart of good development work.",
     "Evaluations, strategies and business cases only create value if people can actually use them. Helen turns dense technical material into clear, persuasive language that partners and communities can act on.",
     "It is fitting recognition, and a reminder that clarity is not decoration — it is how good ideas travel.",
   ]},
  {id:"broadcasting-eval", date:"2023-11-02", cat:"Published", fill:"fill-coast",
   title:"Pacific Broadcasting Programme evaluation published",
   author:"Future Partners", read:3, topics:["Governance & MERL","Education","Evaluation"],
   excerpt:"Our evaluation of MFAT's Pacific Broadcasting Programme (2016–2022) was published on the Ministry of Foreign Affairs & Trade website, examining how the programme supports the region's media landscape.",
   body:[
     "Our evaluation of MFAT's Pacific Broadcasting Programme (2016\u20132022) has been published on the Ministry of Foreign Affairs and Trade website.",
     "The evaluation examined how the programme supports the region's broadcasting and media landscape — testing its goals, and drawing out how it could better serve Pacific audiences and storytellers.",
     "Publishing evaluations openly is part of honest practice: it lets others learn from what worked, what didn't, and why.",
   ]},
  {id:"career-advice", date:"2024-02-14", cat:"Network", fill:"fill-dawn",
   title:"Career advice for the next generation",
   author:"Kirsty Burnett", read:4, topics:["People","Partnerships"],
   excerpt:"Kirsty shares what she's learned across a career in international development with people starting out in the sector.",
   body:[
     "Across a career in international development, Director Kirsty Burnett has learned that the work is, above all, about relationships — and she shares that hard-won perspective with people starting out in the sector.",
     "Her advice is practical: get into the field, listen more than you talk, and remember that local knowledge is expertise. Credibility in this sector is earned alongside partners, not over them.",
     "Mentoring the next generation is part of how Future Partners gives back — and how the values that guide our work get passed on.",
   ]},
  {id:"landfill-drone", date:"2023-09-25", cat:"From the field", fill:"fill-earth",
   title:"Surveying landfills by drone",
   author:"Alice Leney", read:3, topics:["WASH","Climate & environment","Kiribati"],
   excerpt:"Drone surveys are giving Pacific waste programmes a clearer, safer picture of landfill volumes — better data for better decisions.",
   body:[
     "On Pacific waste programmes, knowing how much rubbish a landfill actually holds is harder than it sounds — and getting it wrong leads to poor decisions and wasted money.",
     "Drone surveys are changing that. By mapping a site from the air, our teams can estimate volumes accurately and safely, without putting people onto unstable ground.",
     "Better data means better decisions: where to invest, how fast a site is filling, and what a community's waste system needs next.",
   ]},
];
const newsById = id => NEWS.find(n=>n.id===id);
const NEWS_CATS = [...new Set(NEWS.map(n=>n.cat))];

/* ---------- derived site stats (single source of truth) ---------- */
const SITE_STATS = {
  projects: CASES.length,
  countries: new Set(CASES.map(c=>c.country.name)).size,
  stages: CYCLE.length,
  people: PEOPLE.length,
  regions: REGIONS.length,
};

Object.assign(window, { COUNTRY, CYCLE, STAGE, SECTORS, REGIONS, CLIENT_TYPES, PEOPLE, personById, CLIENTS, TESTIMONIALS, CASES, caseById, NEWS, newsById, NEWS_CATS, SITE_STATS });
